### ISSUE TITLE
Full screen mode for clock

### ISSUE THREAD

**Issue by AlexEhn** [tellurianinteractive/Tellurian.Trains.ModuleMeetingApp#13]
Can a full screen mode be added so the clock can be shown "nice & clean" on a screen?
![Anteckning 2020-06-23 234616](https://user-images.githubusercontent.com/57874863/85467790-f0127d00-b5ab-11ea-8039-22f0d9346ef9.png)

**Comment by AlexEhn** [comment]
Running Chrome on Windows.

**Comment by fjallemark** [comment]
Browsers support full screen mode. But is there something more you want, for example hide the menu?

**Comment by fjallemark** [comment]
Changed the styling so that side menu is not visible up to 1920 pixel wide screens. Top menu is visible up to 1920 pixels wide.

**Comment by AlexEhn** [comment]
Hi, 

Hiding the menu is a great start, but can it be a hide button as well, and not only based on screen width?

Perhaps add a note that "F11 enters fullscreen mode in most browsers". Just now remembered that function actually. 

I would prefer the font size on the message to be smaller. Have to check how it looks if I remove the text.

**Comment by AlexEhn** [comment]
I think what disturbs me is actually that it is so little space around the time "06:02"

So when checking the time there are alot of "clutter" drawing my attention. For me it is not a quick & fast glance to read the time. 

![image](https://user-images.githubusercontent.com/57874863/85594345-23a2e500-b648-11ea-9322-8b29b8b336c5.png)

**Comment by fjallemark** [comment]
Please submit a pull request with suggested improvements. Note that also weekday and two lines of messages must fit on the screen.
