### ISSUE TITLE
Hard-coded reference to local audio file

### ISSUE THREAD

**Issue by frankgeerlings** [tellurianinteractive/Tellurian.Trains.ModuleMeetingApp#3]
It appears that the following file is missing from the repository, and should be referenced to in a relative path, as opposed to an absolute path:

https://github.com/tellurianinteractive/Tellurian.Trains.ModuleMeetingApp/blob/45827d1d096a15e0f1fec847b4308b1a0bb65b7a/Clock.Server/ClockServer.cs#L160

**Comment by fjallemark** [comment]
Tanks for your comment. This is now solved by making start and stop sound files configurable. The default ringtone is also checked in.
