### ISSUE TITLE
Fikapaus

### ISSUE THREAD

**Issue by fjallemark** [tellurianinteractive/Tellurian.Trains.ModuleMeetingApp#4]
Add "Fikapaus" to reasons to pause game. "Fikapaus" is Swedish for coffee break.

**Comment by danielb987** [comment]
Maybe add "Train derailment", if a major derailment has occured?

If "Coffee break" is added, I suggest adding "Lunch break" as well.

**Comment by fjallemark** [comment]
> If "Coffee break" is added, I suggest adding "Lunch break" as well.
Lunch break is already implemented.

**Comment by fjallemark** [comment]
Coffe brake is now implemented in 2.1.3.
