### ISSUE TITLE
Increased duration until a used clock is deleted

### ISSUE THREAD

**Issue by AlexEhn** [tellurianinteractive/Tellurian.Trains.ModuleMeetingApp#57]
The clock app is working fine, even got it to work on a RPi. :) 

However, one thing really frustrates me. And that is that the clock I create for a module meeting is deleted every day. 
A typical module meeting spans over 3-4 days, and as it is now I need to recreate the clock for the meeting every morning before traffic can start. 

This is a pain for thee resons: 
- I have to recreate the clock every day
- Unless I manage to recreate the clock with the same password and setting the users need to update their access to the clock.
- I cannot prepare the clock in advance at home, I'm forced to do it on the morning of the first traffic day. There are a million things to do to get a traffic game going, being forced to create the clock as well, is an unnecessary pain. If the clock can be prepared in advance the participants can prepare it at home where they have time to do it.

I understand that the active clocks needs to be deleted at some point but I have two suggestions:
1. Delete all clocks on Tuesdays and not every day. Tuesday is probably a good day since module meetings are seldom running between Mondays and Tuesdays
2. Open a field or parameter in the Clock Admin where a date can be entered for when the clock should be deleted, maximum 14 days from the date when the clock is created. If no date is entered, the clock can be removed every day as per the current design. 

Thank you.

**Comment by fjallemark** [comment]
From release 3.6.1 can the default clock be configured i *appsettnings.json* when you run the clock server locally. 

This does not solve the issue for the cloud clock. I suggest using clock name and password easy to remember. Also not that only the *clock name* is necessary for others to access the clock, no password is needed. The same *user password* is needed only if you want other users to stop the clock.

**Comment by fjallemark** [comment]
I have decided that not do anyting in this matter of several reasons:
- It takes just a minute to recreate a cloud clock. 
- It is complicated to make a reliable way to override the behaviour in the cloud without increasing cost of operation.
