### ISSUE TITLE
Extract support for MR-clock and sounds to separate app

### ISSUE THREAD

**Issue by fjallemark** [tellurianinteractive/Tellurian.Trains.ModuleMeetingApp#8]
When running the cloud version, there is currently no support for MR-clock and clock start/stop sound. By extracting these functions to a separate application that fetches time from any clock, cloud or local, the MR-clock support and sounds functions will work regardless of running in cloud or local.

**Comment by fjallemark** [comment]
Support for MR-clock is dropped, because it never is used at meetings so far.

**Comment by AlexEhn** [comment]
MR-Clock is the only clock we use within N-Re.
